nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Disposition']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/': # Permet CORS uniquement pour les routes API
            allow_origin: ['http://localhost:4200']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            expose_headers: ['Content-Disposition']
            max_age: 3600
